name: Dependency Check

on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - name: Run npm audit
        id: audit
        run: npm audit --production --audit-level=high --json > audit-report.json
        continue-on-error: true
      - name: Run npm outdated
        run: npm outdated --json > outdated-report.json || true
        continue-on-error: true
      - name: Upload dependency reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dependency-reports
          path: |
            audit-report.json
            outdated-report.json
      - name: Fail on high severity vulnerabilities
        if: steps.audit.outcome == 'failure'
        run: exit 1
